from django.urls import path

from .views import (
    BlockConversionApplyView,
    ChapterBlockConversionSuggestionView,
    ChapterBlockListView,
    ChapterBlockUpdateView,
    ChapterBlockVersionDetailView,
    ChapterBlockVersionListView,
    ChapterContextVisibilityView,
    ChapterDetailView,
    ChapterGeneralSuggestionPromptView,
    ChapterGeneralSuggestionView,
    ChapterParagraphSuggestionPromptView,
    ChapterParagraphSuggestionView,
    EditorView,
    LibraryBookChaptersView,
    LibraryBookContextItemDetailView,
    LibraryBookContextItemsView,
    LibraryBookContextView,
    LibraryBookDetailView,
    LibraryBooksView,
)

urlpatterns = [
    path("library/books/", LibraryBooksView.as_view(), name="library-books"),
    path(
        "library/books/<str:book_id>/",
        LibraryBookDetailView.as_view(),
        name="library-book-detail",
    ),
    path(
        "library/books/<str:book_id>/context/",
        LibraryBookContextView.as_view(),
        name="library-book-context",
    ),
    path(
        "library/books/<str:book_id>/context/items/",
        LibraryBookContextItemsView.as_view(),
        name="library-book-context-items",
    ),
    path(
        "library/books/<str:book_id>/context/items/<str:section_slug>/<str:item_id>/",
        LibraryBookContextItemDetailView.as_view(),
        name="library-book-context-item-detail",
    ),
    path(
        "library/books/<str:book_id>/chapters/",
        LibraryBookChaptersView.as_view(),
        name="library-book-chapters",
    ),
    path(
        "library/chapters/<str:chapter_id>/",
        ChapterDetailView.as_view(),
        name="library-chapter-detail",
    ),
    path(
        "library/chapters/<str:chapter_id>/blocks/",
        ChapterBlockListView.as_view(),
        name="library-chapter-blocks",
    ),
    path(
        "library/chapters/<str:chapter_id>/blocks/<str:block_id>/",
        ChapterBlockUpdateView.as_view(),
        name="library-chapter-block-update",
    ),
    path(
        "library/chapters/<str:chapter_id>/blocks/<str:block_id>/versions/",
        ChapterBlockVersionListView.as_view(),
        name="library-chapter-block-versions",
    ),
    path(
        "library/chapters/<str:chapter_id>/blocks/<str:block_id>/versions/<int:version>/",
        ChapterBlockVersionDetailView.as_view(),
        name="library-chapter-block-version-detail",
    ),
    path(
        "library/chapters/<str:chapter_id>/context-visibility/",
        ChapterContextVisibilityView.as_view(),
        name="library-chapter-context-visibility",
    ),
    path(
        "library/chapters/<str:chapter_id>/paragraph-suggestion/",
        ChapterParagraphSuggestionView.as_view(),
        name="library-chapter-paragraph-suggestion",
    ),
    path(
        "library/chapters/<str:chapter_id>/paragraph-suggestion/prompt/",
        ChapterParagraphSuggestionPromptView.as_view(),
        name="library-chapter-paragraph-suggestion-prompt",
    ),
    path(
        "library/chapters/<str:chapter_id>/general-suggestions/",
        ChapterGeneralSuggestionView.as_view(),
        name="library-chapter-general-suggestions",
    ),
    path(
        "library/chapters/<str:chapter_id>/general-suggestions/prompt/",
        ChapterGeneralSuggestionPromptView.as_view(),
        name="library-chapter-general-suggestions-prompt",
    ),
    path(
        "library/chapters/<str:chapter_id>/block-conversions/",
        ChapterBlockConversionSuggestionView.as_view(),
        name="library-chapter-block-conversion",
    ),
    path(
        "library/block-conversions/<uuid:conversion_id>/apply/",
        BlockConversionApplyView.as_view(),
        name="library-block-conversion-apply",
    ),
    path("editor/", EditorView.as_view(), name="editor"),
]
