# Generated by Django 5.2.4 on 2025-10-12 23:16

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("synopsis", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LibrarySection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("default_open", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="studio.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "ordinal", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChapterBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("paragraph", "Paragraph"),
                            ("dialogue", "Dialogue"),
                            ("scene_boundary", "Scene boundary"),
                            ("metadata", "Metadata"),
                        ],
                        max_length=32,
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="studio.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="LibraryContextItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_id", models.CharField(max_length=64)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("world", "World"),
                            ("styleTone", "Style & Tone"),
                            ("chapter", "Chapter"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("facts", models.TextField(blank=True)),
                ("tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("checked", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="studio.librarysection",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order", "item_id"],
                "unique_together": {("section", "item_id")},
            },
        ),
    ]
