# Generated by Django 5.2.7 on 2025-10-13 17:46

import django.db.models.deletion
from django.db import migrations, models


def assign_sections_to_sample_book(apps, schema_editor):
    Book = apps.get_model("studio", "Book")
    LibrarySection = apps.get_model("studio", "LibrarySection")

    sample_book = None
    try:
        sample_book = Book.objects.get(pk="bk-karamazov")
    except Book.DoesNotExist:
        sample_book = Book.objects.order_by("id").first()

    updates = []
    for section in LibrarySection.objects.all():
        changed = False
        if not getattr(section, "slug", None):
            section.slug = section.id
            changed = True
        if sample_book and getattr(section, "book_id", None) != sample_book.id:
            section.book_id = sample_book.id
            changed = True
        if changed:
            updates.append(section)

    if updates:
        LibrarySection.objects.bulk_update(updates, ["slug", "book"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_load_sample_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarysection",
            name="slug",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="librarysection",
            name="book",
            field=models.ForeignKey(
                default="bk-karamazov",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_sections",
                to="studio.book",
            ),
        ),
        migrations.AddField(
            model_name="librarycontextitem",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_items",
                to="studio.chapter",
            ),
        ),
        migrations.RunPython(assign_sections_to_sample_book, noop),
        migrations.AlterField(
            model_name="librarysection",
            name="slug",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="librarysection",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_sections",
                to="studio.book",
            ),
        ),
        migrations.AddConstraint(
            model_name="librarysection",
            constraint=models.UniqueConstraint(fields=("book", "slug"), name="uniq_section_book_slug"),
        ),
    ]
