# Generated by Django 5.2.7 on 2025-10-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_book_context_scope"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="librarysection",
            options={"ordering": ["book", "order", "slug"]},
        ),
    ]
