# Generated by Django 5.2.7 on 2025-10-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_alter_librarysection_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterContextVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_visibilities",
                        to="studio.chapter",
                    ),
                ),
                (
                    "context_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_visibilities",
                        to="studio.librarycontextitem",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "chapter",
                    "context_item__section__order",
                    "context_item__order",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chapter", "context_item"), name="uniq_chapter_context_visibility"
                    )
                ],
            },
        ),
    ]
