# Generated by Django 5.2.7 on 2025-10-15 15:40

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_chapterblock_active_version_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterBlockConversion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_text", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("context_block_id", models.CharField(blank=True, max_length=64)),
                ("provider", models.CharField(default="gemini", max_length=64)),
                ("model_name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("discarded", "Discarded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "suggested_blocks",
                    models.JSONField(
                        default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "applied_block_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_conversions",
                        to="studio.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
